-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('talkbox_pb')


local TALK_RESULT = protobuf.Descriptor();
local TALK_RESULT_ID_FIELD = protobuf.FieldDescriptor();
local TALK_CREATE = protobuf.Descriptor();
local TALK_CREATE_USERID_FIELD = protobuf.FieldDescriptor();
local TALK_CREATE_NAME_FIELD = protobuf.FieldDescriptor();
local TALK_USERS = protobuf.Descriptor();
local TALK_USERS_TALK_USER = protobuf.Descriptor();
local TALK_USERS_TALK_USER_USERID_FIELD = protobuf.FieldDescriptor();
local TALK_USERS_TALK_USER_NAME_FIELD = protobuf.FieldDescriptor();
local TALK_USERS_USERS_FIELD = protobuf.FieldDescriptor();
local TALK_MESSAGE = protobuf.Descriptor();
local TALK_MESSAGE_FROMUSERID_FIELD = protobuf.FieldDescriptor();
local TALK_MESSAGE_TOUSERID_FIELD = protobuf.FieldDescriptor();
local TALK_MESSAGE_MSG_FIELD = protobuf.FieldDescriptor();

TALK_RESULT_ID_FIELD.name = "id"
TALK_RESULT_ID_FIELD.full_name = ".talkbox.talk_result.id"
TALK_RESULT_ID_FIELD.number = 1
TALK_RESULT_ID_FIELD.index = 0
TALK_RESULT_ID_FIELD.label = 2
TALK_RESULT_ID_FIELD.has_default_value = false
TALK_RESULT_ID_FIELD.default_value = 0
TALK_RESULT_ID_FIELD.type = 5
TALK_RESULT_ID_FIELD.cpp_type = 1

TALK_RESULT.name = "talk_result"
TALK_RESULT.full_name = ".talkbox.talk_result"
TALK_RESULT.nested_types = {}
TALK_RESULT.enum_types = {}
TALK_RESULT.fields = {TALK_RESULT_ID_FIELD}
TALK_RESULT.is_extendable = false
TALK_RESULT.extensions = {}
TALK_CREATE_USERID_FIELD.name = "userid"
TALK_CREATE_USERID_FIELD.full_name = ".talkbox.talk_create.userid"
TALK_CREATE_USERID_FIELD.number = 1
TALK_CREATE_USERID_FIELD.index = 0
TALK_CREATE_USERID_FIELD.label = 2
TALK_CREATE_USERID_FIELD.has_default_value = false
TALK_CREATE_USERID_FIELD.default_value = 0
TALK_CREATE_USERID_FIELD.type = 5
TALK_CREATE_USERID_FIELD.cpp_type = 1

TALK_CREATE_NAME_FIELD.name = "name"
TALK_CREATE_NAME_FIELD.full_name = ".talkbox.talk_create.name"
TALK_CREATE_NAME_FIELD.number = 2
TALK_CREATE_NAME_FIELD.index = 1
TALK_CREATE_NAME_FIELD.label = 2
TALK_CREATE_NAME_FIELD.has_default_value = false
TALK_CREATE_NAME_FIELD.default_value = ""
TALK_CREATE_NAME_FIELD.type = 9
TALK_CREATE_NAME_FIELD.cpp_type = 9

TALK_CREATE.name = "talk_create"
TALK_CREATE.full_name = ".talkbox.talk_create"
TALK_CREATE.nested_types = {}
TALK_CREATE.enum_types = {}
TALK_CREATE.fields = {TALK_CREATE_USERID_FIELD, TALK_CREATE_NAME_FIELD}
TALK_CREATE.is_extendable = false
TALK_CREATE.extensions = {}
TALK_USERS_TALK_USER_USERID_FIELD.name = "userid"
TALK_USERS_TALK_USER_USERID_FIELD.full_name = ".talkbox.talk_users.talk_user.userid"
TALK_USERS_TALK_USER_USERID_FIELD.number = 1
TALK_USERS_TALK_USER_USERID_FIELD.index = 0
TALK_USERS_TALK_USER_USERID_FIELD.label = 2
TALK_USERS_TALK_USER_USERID_FIELD.has_default_value = false
TALK_USERS_TALK_USER_USERID_FIELD.default_value = 0
TALK_USERS_TALK_USER_USERID_FIELD.type = 5
TALK_USERS_TALK_USER_USERID_FIELD.cpp_type = 1

TALK_USERS_TALK_USER_NAME_FIELD.name = "name"
TALK_USERS_TALK_USER_NAME_FIELD.full_name = ".talkbox.talk_users.talk_user.name"
TALK_USERS_TALK_USER_NAME_FIELD.number = 2
TALK_USERS_TALK_USER_NAME_FIELD.index = 1
TALK_USERS_TALK_USER_NAME_FIELD.label = 2
TALK_USERS_TALK_USER_NAME_FIELD.has_default_value = false
TALK_USERS_TALK_USER_NAME_FIELD.default_value = ""
TALK_USERS_TALK_USER_NAME_FIELD.type = 9
TALK_USERS_TALK_USER_NAME_FIELD.cpp_type = 9

TALK_USERS_TALK_USER.name = "talk_user"
TALK_USERS_TALK_USER.full_name = ".talkbox.talk_users.talk_user"
TALK_USERS_TALK_USER.nested_types = {}
TALK_USERS_TALK_USER.enum_types = {}
TALK_USERS_TALK_USER.fields = {TALK_USERS_TALK_USER_USERID_FIELD, TALK_USERS_TALK_USER_NAME_FIELD}
TALK_USERS_TALK_USER.is_extendable = false
TALK_USERS_TALK_USER.extensions = {}
TALK_USERS_TALK_USER.containing_type = TALK_USERS
TALK_USERS_USERS_FIELD.name = "users"
TALK_USERS_USERS_FIELD.full_name = ".talkbox.talk_users.users"
TALK_USERS_USERS_FIELD.number = 1
TALK_USERS_USERS_FIELD.index = 0
TALK_USERS_USERS_FIELD.label = 3
TALK_USERS_USERS_FIELD.has_default_value = false
TALK_USERS_USERS_FIELD.default_value = {}
TALK_USERS_USERS_FIELD.message_type = TALK_USERS_TALK_USER
TALK_USERS_USERS_FIELD.type = 11
TALK_USERS_USERS_FIELD.cpp_type = 10

TALK_USERS.name = "talk_users"
TALK_USERS.full_name = ".talkbox.talk_users"
TALK_USERS.nested_types = {TALK_USERS_TALK_USER}
TALK_USERS.enum_types = {}
TALK_USERS.fields = {TALK_USERS_USERS_FIELD}
TALK_USERS.is_extendable = false
TALK_USERS.extensions = {}
TALK_MESSAGE_FROMUSERID_FIELD.name = "fromuserid"
TALK_MESSAGE_FROMUSERID_FIELD.full_name = ".talkbox.talk_message.fromuserid"
TALK_MESSAGE_FROMUSERID_FIELD.number = 1
TALK_MESSAGE_FROMUSERID_FIELD.index = 0
TALK_MESSAGE_FROMUSERID_FIELD.label = 2
TALK_MESSAGE_FROMUSERID_FIELD.has_default_value = false
TALK_MESSAGE_FROMUSERID_FIELD.default_value = 0
TALK_MESSAGE_FROMUSERID_FIELD.type = 5
TALK_MESSAGE_FROMUSERID_FIELD.cpp_type = 1

TALK_MESSAGE_TOUSERID_FIELD.name = "touserid"
TALK_MESSAGE_TOUSERID_FIELD.full_name = ".talkbox.talk_message.touserid"
TALK_MESSAGE_TOUSERID_FIELD.number = 2
TALK_MESSAGE_TOUSERID_FIELD.index = 1
TALK_MESSAGE_TOUSERID_FIELD.label = 2
TALK_MESSAGE_TOUSERID_FIELD.has_default_value = false
TALK_MESSAGE_TOUSERID_FIELD.default_value = 0
TALK_MESSAGE_TOUSERID_FIELD.type = 5
TALK_MESSAGE_TOUSERID_FIELD.cpp_type = 1

TALK_MESSAGE_MSG_FIELD.name = "msg"
TALK_MESSAGE_MSG_FIELD.full_name = ".talkbox.talk_message.msg"
TALK_MESSAGE_MSG_FIELD.number = 3
TALK_MESSAGE_MSG_FIELD.index = 2
TALK_MESSAGE_MSG_FIELD.label = 2
TALK_MESSAGE_MSG_FIELD.has_default_value = false
TALK_MESSAGE_MSG_FIELD.default_value = ""
TALK_MESSAGE_MSG_FIELD.type = 9
TALK_MESSAGE_MSG_FIELD.cpp_type = 9

TALK_MESSAGE.name = "talk_message"
TALK_MESSAGE.full_name = ".talkbox.talk_message"
TALK_MESSAGE.nested_types = {}
TALK_MESSAGE.enum_types = {}
TALK_MESSAGE.fields = {TALK_MESSAGE_FROMUSERID_FIELD, TALK_MESSAGE_TOUSERID_FIELD, TALK_MESSAGE_MSG_FIELD}
TALK_MESSAGE.is_extendable = false
TALK_MESSAGE.extensions = {}

talk_create = protobuf.Message(TALK_CREATE)
talk_message = protobuf.Message(TALK_MESSAGE)
talk_result = protobuf.Message(TALK_RESULT)
talk_users = protobuf.Message(TALK_USERS)
talk_users.talk_user = protobuf.Message(TALK_USERS_TALK_USER)

