-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('users_pb')


local USERS_INFO = protobuf.Descriptor();
local USERS_INFO_USERID_FIELD = protobuf.FieldDescriptor();
local USERS_INFO_MONEY_FIELD = protobuf.FieldDescriptor();
local USERS_INFO_EXP_FIELD = protobuf.FieldDescriptor();
local USERS_INFO_LEVEL_FIELD = protobuf.FieldDescriptor();
local USERS_INFO_RANKSOCRE_FIELD = protobuf.FieldDescriptor();
local USERS_INFO_GEM_FIELD = protobuf.FieldDescriptor();
local USERS_INFO_HEAD_FIELD = protobuf.FieldDescriptor();
local USERS_INFO_AWARDKEY_FIELD = protobuf.FieldDescriptor();

USERS_INFO_USERID_FIELD.name = "userid"
USERS_INFO_USERID_FIELD.full_name = ".users.users_info.userid"
USERS_INFO_USERID_FIELD.number = 1
USERS_INFO_USERID_FIELD.index = 0
USERS_INFO_USERID_FIELD.label = 2
USERS_INFO_USERID_FIELD.has_default_value = false
USERS_INFO_USERID_FIELD.default_value = 0
USERS_INFO_USERID_FIELD.type = 5
USERS_INFO_USERID_FIELD.cpp_type = 1

USERS_INFO_MONEY_FIELD.name = "money"
USERS_INFO_MONEY_FIELD.full_name = ".users.users_info.money"
USERS_INFO_MONEY_FIELD.number = 2
USERS_INFO_MONEY_FIELD.index = 1
USERS_INFO_MONEY_FIELD.label = 1
USERS_INFO_MONEY_FIELD.has_default_value = false
USERS_INFO_MONEY_FIELD.default_value = 0
USERS_INFO_MONEY_FIELD.type = 5
USERS_INFO_MONEY_FIELD.cpp_type = 1

USERS_INFO_EXP_FIELD.name = "exp"
USERS_INFO_EXP_FIELD.full_name = ".users.users_info.exp"
USERS_INFO_EXP_FIELD.number = 3
USERS_INFO_EXP_FIELD.index = 2
USERS_INFO_EXP_FIELD.label = 1
USERS_INFO_EXP_FIELD.has_default_value = false
USERS_INFO_EXP_FIELD.default_value = 0
USERS_INFO_EXP_FIELD.type = 5
USERS_INFO_EXP_FIELD.cpp_type = 1

USERS_INFO_LEVEL_FIELD.name = "level"
USERS_INFO_LEVEL_FIELD.full_name = ".users.users_info.level"
USERS_INFO_LEVEL_FIELD.number = 4
USERS_INFO_LEVEL_FIELD.index = 3
USERS_INFO_LEVEL_FIELD.label = 1
USERS_INFO_LEVEL_FIELD.has_default_value = false
USERS_INFO_LEVEL_FIELD.default_value = 0
USERS_INFO_LEVEL_FIELD.type = 5
USERS_INFO_LEVEL_FIELD.cpp_type = 1

USERS_INFO_RANKSOCRE_FIELD.name = "ranksocre"
USERS_INFO_RANKSOCRE_FIELD.full_name = ".users.users_info.ranksocre"
USERS_INFO_RANKSOCRE_FIELD.number = 5
USERS_INFO_RANKSOCRE_FIELD.index = 4
USERS_INFO_RANKSOCRE_FIELD.label = 1
USERS_INFO_RANKSOCRE_FIELD.has_default_value = false
USERS_INFO_RANKSOCRE_FIELD.default_value = 0
USERS_INFO_RANKSOCRE_FIELD.type = 5
USERS_INFO_RANKSOCRE_FIELD.cpp_type = 1

USERS_INFO_GEM_FIELD.name = "gem"
USERS_INFO_GEM_FIELD.full_name = ".users.users_info.gem"
USERS_INFO_GEM_FIELD.number = 6
USERS_INFO_GEM_FIELD.index = 5
USERS_INFO_GEM_FIELD.label = 1
USERS_INFO_GEM_FIELD.has_default_value = false
USERS_INFO_GEM_FIELD.default_value = 0
USERS_INFO_GEM_FIELD.type = 5
USERS_INFO_GEM_FIELD.cpp_type = 1

USERS_INFO_HEAD_FIELD.name = "head"
USERS_INFO_HEAD_FIELD.full_name = ".users.users_info.head"
USERS_INFO_HEAD_FIELD.number = 7
USERS_INFO_HEAD_FIELD.index = 6
USERS_INFO_HEAD_FIELD.label = 1
USERS_INFO_HEAD_FIELD.has_default_value = false
USERS_INFO_HEAD_FIELD.default_value = 0
USERS_INFO_HEAD_FIELD.type = 5
USERS_INFO_HEAD_FIELD.cpp_type = 1

USERS_INFO_AWARDKEY_FIELD.name = "awardkey"
USERS_INFO_AWARDKEY_FIELD.full_name = ".users.users_info.awardkey"
USERS_INFO_AWARDKEY_FIELD.number = 8
USERS_INFO_AWARDKEY_FIELD.index = 7
USERS_INFO_AWARDKEY_FIELD.label = 1
USERS_INFO_AWARDKEY_FIELD.has_default_value = false
USERS_INFO_AWARDKEY_FIELD.default_value = 0
USERS_INFO_AWARDKEY_FIELD.type = 5
USERS_INFO_AWARDKEY_FIELD.cpp_type = 1

USERS_INFO.name = "users_info"
USERS_INFO.full_name = ".users.users_info"
USERS_INFO.nested_types = {}
USERS_INFO.enum_types = {}
USERS_INFO.fields = {USERS_INFO_USERID_FIELD, USERS_INFO_MONEY_FIELD, USERS_INFO_EXP_FIELD, USERS_INFO_LEVEL_FIELD, USERS_INFO_RANKSOCRE_FIELD, USERS_INFO_GEM_FIELD, USERS_INFO_HEAD_FIELD, USERS_INFO_AWARDKEY_FIELD}
USERS_INFO.is_extendable = false
USERS_INFO.extensions = {}

users_info = protobuf.Message(USERS_INFO)

