rm -rf log_me/*.txt
rm -rf log_me/*.log
rm -rf log_me/*.txt
rm -rf log_me/month/*.txt
rm -rf log_me/day/*.txt
rm -rf log_me/hour/*.txt
rm -rf log_me/min/*.txt
rm -rf log_me/gm/*.txt
rm -rf log_me/sys/*.txt
rm -rf log_me/event/*.txt
rm -rf log_me/hour/url/*.txt
